### PR TITLE
deleted provider info

### PR DESCRIPTION
**Pull request by VaishnaviGopal**

### CODE REVIEW

**Comment by mekaufman** [comment]
@VaishnaviGopal The action isn't really exporting, but setting and retrieving the user name and API key.

Also, I'm not sure we can just change the set variable names from SoftLayer. And, I see you removed them from the required variables, but as I understand they are required. Do you possibly have different information that was the basis for this PR?

**Comment by davetropeano** [comment]
It isn't clear at all that using ALLCAPS for variable names is common in the Terraform ecosystem or that the other diffs add much to the value of this template.

**Comment by hkantare** [comment]
We will be holding this PR for future..This will be done when there is less time pressure.

**Review by SaiKrishnaMohan7 — CHANGES_REQUESTED** [review]
Making sure this doesn't get merged in accidentally

DO NOT MERGE

**Comment by geethasathyamurthy** [comment]
Closing this PR, as the template is supporting TFv0.12 or more, hence the block to download the Terraform provider is needed.

**Pull request closed without merging**
